
export const GRATICULE_DEFAULTS = {
  BORDER_STROKE: '#000000',
  BORDER_STROKE_WIDTH: '1px',
  BACKGROUND_FILL: '#a4bac7',
  LINES_STROKE: '#888888',
  LINES_STROKE_WIDTH: '0.5px',
  LINES_STROKE_OPACITY: '0.5'
};

export const GEODATA_DEFAULTS = {
  BACKGROUND_FILL: '#ffffff',
  LINES_STROKE: '#000000',
  LINES_STROKE_WIDTH: '0.5px',
  LINES_STROKE_OPACITY: '0.5'
};

export const SHAPE_CIRCLE_DEFAULTS = {
  BACKGROUND_OPACITY: '0.75',
  BACKGROUND_FILL: '#ffffff',
  LINES_STROKE: '#000000',
  LINES_STROKE_WIDTH: '0.5px',
  LINES_STROKE_OPACITY: '0.5'
};

export const SHAPE_POINT_DEFAULTS = {
  BACKGROUND_OPACITY: '0.75',
  BACKGROUND_FILL: '#ffffff',
  LINES_STROKE: '#000000',
  LINES_STROKE_WIDTH: '0.5px',
  LINES_STROKE_OPACITY: '0.5'
};